[package]
name = "nuts-container"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["backend", "container"]
backend = ["dep:serde"]
container = ["backend", "dep:nuts-bytes", "dep:openssl", "dep:openssl-sys", "dep:serde"]
debug-plain-keys = []

[dependencies]
log = "0.4.14"
nuts-bytes = { version = "0.1.0", optional = true }
openssl ={ version = "0.10.57", optional = true }
openssl-sys = { version = "0.9.93", optional = true }
serde = { version = "1.0.152", features = ["derive"], optional = true }
