[package]
name = "nuts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
nuts-tool = ["anyhow", "clap", "env_logger"]
default = ["nuts-tool"]

[dependencies]
log = "0.4.14"
uuid = { version = "1.1.2", features = ["v4"] }

# used for nuts-tool
anyhow = { version = "1.0.44", optional = true }
clap = { version = "2.33.3", optional = true }
env_logger = { version = "0.9.0", optional = true }

[build-dependencies]
pkg-config = "0.3.25"

[[bin]]
name = "nuts"
required-features = ["nuts-tool"]
