[package]
name = "nuts-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
clap = "2.33.3"
env_logger = "0.9.0"
home = "0.5.4"
log = "0.4.14"
nuts = { path = "../nuts" }
nuts-backend = { path = "../nuts-backend" }
nutsbackend-directory = { path = "../backends/directory" }
rpassword = "5.0.1"
serde = "1.0.152"
toml = "0.6.0"
