[package]
name = "nuts-tool"
version = "0.3.8"
edition = "2018"
rust-version = "1.66"
authors = ["Robin Doer <robin@robind.de>"]
description = "A cmdline utility for the nuts container"
categories = ["cryptography", "command-line-utilities"]
keywords = ["secure", "storage", "nuts"]
repository = "https://github.com/drobin/nuts-tool.git"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "=1.0.75"
chrono = "=0.4.31"
clap = { version = "=3.2.23", features = ["color", "derive", "env"] }
colored = "=2.0.4"
env_logger = "=0.9.3"
home = "=0.5.5"
log = "=0.4.20"
nuts-archive = { path = "../nuts-archive", version = "=0.2.4" }
nuts-container = { path = "../nuts-container", version = "=0.2.2" }
nuts-directory = { path = "../nuts-directory", version = "=0.3.2" }
rpassword = "=7.2.0"

[build-dependencies]
cargo_metadata = "=0.18.1"

[[bin]]
name = "nuts"
path = "src/main.rs"
