[package]
name = "nuts-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
clap = "2.33.3"
env_logger = "0.9.0"
log = "0.4.14"
nuts = { path = "../nuts" }
rpassword = "5.0.1"
