name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --features=plugin
    - name: Clippy
      run: cargo clippy --all-features -- -Dwarnings
    - name: Run tests
      run: cargo test --all-features
